##This function will inverse the matrix
##creates a special "matrix" that can cache its inverse

makeCacheMatrix <- function(x = matrix()) {

m <- NULL
set <- function(y) {
    x <<- y
    m <<- NULL
}
get <- function() x
setinverse <- function(inverse) m <<- inverse
getinverse <- function() m
list(set = set, get = get,
     setinverse = setinverse,
     getinverse = getinverse)
}

##This function will compute what was obtained by the previous one (the inverted matrix)
##If the inverse has already been calculated, then the cachesolve should retrieve the inverse from the cache
##This tipe of function can be done with the solve function in R too

cacheSolve <- function(x, ...) {

## Return a matrix that is the inverse of 'x'
m <- x$getinverse()
if(!is.null(m)) {
    message("getting cached data")
    return(m)
}
data <- x$get()
m <- solve(data, ...)
x$setinverse(m)
m
}
